Repository hashicorp/terraform-provider-cloudinit, pull requests merged in 2023-01, with the labels that each got.

#84 .github/workflows: Pin actions versions to SHAs
  .github/workflows/add-content-to-project.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/S

#85 Update setup-go to use `go.mod`
  .github/workflows/release.yml
  .github/workflows/test.yml
  .go-version
Labels: size/XS

#86 Add Jira automation
  .github/workflows/jira-sync.yml
  .github/workflows/send-to-jira.yml
Labels: size/M

#91 Rename `IMPROVEMENTS` Changie label to `ENCHANCEMENTS`
  .changie.yaml
Labels: size/XS
