Repository hashicorp/terraform-provider-cloudinit, pull requests merged in 2024-11, with the labels that each got.

#280 Add new build Action
  .github/workflows/build.yml
  .go-version
  version/VERSION
Labels: size/M

#283 build Action: get Go version using go.mod
  .github/workflows/build.yml
Labels: size/XS

#284 build Action: set bin_name to match .goreleaser.yml
  .github/workflows/build.yml
Labels: size/XS

#286 Update build Action to resolve warnings
  .github/workflows/build.yml
  .release/oss-release-metadata.hcl
  .release/security-scan.hcl
  .release/terraform-provider-cloudinit-artifacts.hcl
Labels: size/S

#287 Fix reusable Action reference
  .github/workflows/build.yml
Labels: size/XS

#289 doc: fix minor typo
  docs/data-sources/config.md
  docs/resources/config.md
  internal/provider/data_source_cloudinit_config.go
  internal/provider/resource_cloudinit_config.go
Labels: size/XS

#290 cdktf: update documentation
  docs/cdktf/python/data-sources/config.md
  docs/cdktf/python/resources/config.md
  docs/cdktf/typescript/data-sources/config.md
  docs/cdktf/typescript/resources/config.md
Labels: size/XS
