Repository hashicorp/terraform-provider-cloudinit, pull requests merged in 2025-03, with the labels that each got.

#320 Upload registry manifest as an Actions artifact
  .github/workflows/build.yml
Labels: size/XS

#321 Fix terraform registry manifest filename
  .github/workflows/build.yml
Labels: size/XS

#322 Prepare for `v2.3.7-alpha1` release
  .changes/2.3.7-alpha1.md
  CHANGELOG.md
  version/VERSION
Labels: size/XS

#328 Fix post-promotion workflow name
  .release/ci.hcl
Labels: size/XS

#331 chore: Update minimum Go version in module
  README.md
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: dependencies, size/S

#336 Prepare for `v2.3.7-alpha.2` release
  .github/workflows/build.yml
  .release/ci.hcl
  version/VERSION
Labels: size/M
